package com.example.taskmanager.common.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TASKS
 */
public class Task {
    /**
     * Database Column Remarks:
     *   タスクID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   タイトル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   説明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   ステータス（TODO/IN_PROGRESS/DONE）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   優先度（LOW/MEDIUM/HIGH）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.PRIORITY
     *
     * @mbg.generated
     */
    private String priority;

    /**
     * Database Column Remarks:
     *   カテゴリーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.CATEGORY_ID
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   期限日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DUE_DATE
     *
     * @mbg.generated
     */
    private LocalDate dueDate;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.CREATED_AT
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.UPDATED_AT
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.ID
     *
     * @return the value of TASKS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.ID
     *
     * @param id the value for TASKS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.TITLE
     *
     * @return the value of TASKS.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.TITLE
     *
     * @param title the value for TASKS.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DESCRIPTION
     *
     * @return the value of TASKS.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DESCRIPTION
     *
     * @param description the value for TASKS.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.STATUS
     *
     * @return the value of TASKS.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.STATUS
     *
     * @param status the value for TASKS.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.PRIORITY
     *
     * @return the value of TASKS.PRIORITY
     *
     * @mbg.generated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.PRIORITY
     *
     * @param priority the value for TASKS.PRIORITY
     *
     * @mbg.generated
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.CATEGORY_ID
     *
     * @return the value of TASKS.CATEGORY_ID
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.CATEGORY_ID
     *
     * @param categoryId the value for TASKS.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DUE_DATE
     *
     * @return the value of TASKS.DUE_DATE
     *
     * @mbg.generated
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DUE_DATE
     *
     * @param dueDate the value for TASKS.DUE_DATE
     *
     * @mbg.generated
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.CREATED_AT
     *
     * @return the value of TASKS.CREATED_AT
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.CREATED_AT
     *
     * @param createdAt the value for TASKS.CREATED_AT
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.UPDATED_AT
     *
     * @return the value of TASKS.UPDATED_AT
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.UPDATED_AT
     *
     * @param updatedAt the value for TASKS.UPDATED_AT
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}