package com.example.taskmanager.common.entity;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TASK_CATEGORIES
 */
public class TaskCategory {
    /**
     * Database Column Remarks:
     *   カテゴリーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   カテゴリー名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   カテゴリー説明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   表示色（HEXカラーコード）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.COLOR
     *
     * @mbg.generated
     */
    private String color;

    /**
     * Database Column Remarks:
     *   表示順
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.DISPLAY_ORDER
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.CREATED_AT
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK_CATEGORIES.UPDATED_AT
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.ID
     *
     * @return the value of TASK_CATEGORIES.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.ID
     *
     * @param id the value for TASK_CATEGORIES.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.NAME
     *
     * @return the value of TASK_CATEGORIES.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.NAME
     *
     * @param name the value for TASK_CATEGORIES.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.DESCRIPTION
     *
     * @return the value of TASK_CATEGORIES.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.DESCRIPTION
     *
     * @param description the value for TASK_CATEGORIES.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.COLOR
     *
     * @return the value of TASK_CATEGORIES.COLOR
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.COLOR
     *
     * @param color the value for TASK_CATEGORIES.COLOR
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.DISPLAY_ORDER
     *
     * @return the value of TASK_CATEGORIES.DISPLAY_ORDER
     *
     * @mbg.generated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.DISPLAY_ORDER
     *
     * @param displayOrder the value for TASK_CATEGORIES.DISPLAY_ORDER
     *
     * @mbg.generated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.CREATED_AT
     *
     * @return the value of TASK_CATEGORIES.CREATED_AT
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.CREATED_AT
     *
     * @param createdAt the value for TASK_CATEGORIES.CREATED_AT
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK_CATEGORIES.UPDATED_AT
     *
     * @return the value of TASK_CATEGORIES.UPDATED_AT
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK_CATEGORIES.UPDATED_AT
     *
     * @param updatedAt the value for TASK_CATEGORIES.UPDATED_AT
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}