package com.example.taskmanager.common.mapper;

import com.example.taskmanager.common.entity.Task;
import com.example.taskmanager.common.entity.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int insert(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int insertSelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Task row);
}