package com.example.taskmanager.common.mapper;

import com.example.taskmanager.common.entity.TaskCategory;
import com.example.taskmanager.common.entity.TaskCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    long countByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int deleteByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int insert(TaskCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int insertSelective(TaskCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    List<TaskCategory> selectByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    TaskCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TaskCategory row, @Param("example") TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TaskCategory row, @Param("example") TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_CATEGORIES
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskCategory row);
}